services:
  odoo:
    build:
      context: ./odoo/17.0
      dockerfile: ./Dockerfile
    ports:
      - "8069:8069"
    networks:
      - odoo_network
    volumes:
      - ./odoo/config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./odoo/data:/var/lib/odoo
      - ./odoo17.0:/opt/odoo17.0
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:14
    container_name: db
    networks:
      - odoo_network
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "odoo" ]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
networks:
  odoo_network:
    driver: bridge