services:
  odoo13:
    build:
      context: ./odoo/13.0
      dockerfile: ./Dockerfile
    ports:
      - "8069:8069"
    networks:
      - odoo13
    volumes:
      - ./odoo/config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./odoo/data:/var/lib/odoo
      - ./odoo13.0:/opt/odoo13.0
    depends_on:
      db13:
        condition: service_healthy
    environment:
      - HOST=db13
      - USER=odoo
      - PASSWORD=odoo
  db13:
    image: postgres:14
    networks:
      - odoo13
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "odoo" ]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
networks:
  odoo13:
    driver: bridge